## KNearest Regressor

In [14]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=2, noise=10, random_state=42)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [16]:
from sklearn.neighbors import KNeighborsRegressor
regressor = KNeighborsRegressor(n_neighbors=6,algorithm='auto')

In [17]:
regressor.fit(X_train,y_train)

KNeighborsRegressor(n_neighbors=6)

In [18]:
y_pred = regressor.predict(X_test)

In [19]:
print(y_pred)

[ 44.36816359  -1.82674126 -17.77501278 -14.23248527  39.98247345
  16.32474215  62.47359613 -29.37903754 -69.62828115 -11.52925322
  21.80810748  -6.8056688  -68.2122538   56.95832322  17.88875688
   0.73027663 -58.89280399  25.43992007 -30.65682555  24.11830631
  20.70133101  13.82594327 -20.83394064 -42.50851757 -44.01205253
  22.06623323 -59.95999435  57.41364484 -22.02518095  75.16878764
 -76.76262901  35.49887555 -55.89232411  -6.77954881 -50.48642122
  -3.93342619  17.65966891  35.4419457   10.69616371 -52.2084338
  86.76482216  29.84752288  36.64907356 -70.67275387  19.13441662
  20.63748914 -35.35331754  -4.03648265  62.64114459  68.04595243
  59.37221042  75.88137624 -59.7684246  -30.04634947 -50.27233415
 -20.52218402 -33.29603737  33.50360127  89.84335353  33.82278541
  37.59356966   2.91576852 -19.57413326  -5.06042584  -8.02945657
 -18.33906448   4.15920175  22.49622144  -8.48670013 -58.54755482
  40.66439847  82.38542471  59.11937125   2.56693742  65.71314378
 -33.062569

In [20]:
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.9151234135490012
9.238866237248063
137.48092021502467


## KNeighbors Classifier

In [21]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [22]:
from sklearn.datasets import make_classification

X, y = make_classification(
    n_samples=1000, # 1000 observations 
    n_features=3, # 3 total features
     n_redundant=1,
    n_classes=2, # binary target/label 
    random_state=999 
)

In [23]:
X

array([[-0.33504974,  0.02852654,  1.16193084],
       [-1.37746253, -0.4058213 ,  0.44359618],
       [-1.04520026, -0.72334759, -3.10470423],
       ...,
       [-0.75602574, -0.51816111, -2.20382324],
       [ 0.56066316, -0.07335845, -2.15660348],
       [-1.87521902, -1.11380394, -4.04620773]])

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [25]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5,algorithm='auto')

In [26]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [27]:
y_pred = classifier.predict(X_test)

In [28]:
y_pred

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0])

In [29]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [30]:
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[98  5]
 [12 85]]
0.915
              precision    recall  f1-score   support

           0       0.89      0.95      0.92       103
           1       0.94      0.88      0.91        97

    accuracy                           0.92       200
   macro avg       0.92      0.91      0.91       200
weighted avg       0.92      0.92      0.91       200



In [31]:
from sklearn.model_selection import GridSearchCV


In [32]:
param_grid = {
    'n_neighbors':[1,2,3,4,5,6,7,8,9,10]
}

In [33]:
grid = GridSearchCV(estimator=KNeighborsClassifier(),param_grid=param_grid)

In [34]:
grid.fit(X_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [35]:
grid_pred = grid.predict(X_test)

In [36]:
print(confusion_matrix(y_pred,grid_pred))
print(accuracy_score(y_pred,grid_pred))
print(classification_report(y_pred,grid_pred))

[[110   0]
 [  3  87]]
0.985
              precision    recall  f1-score   support

           0       0.97      1.00      0.99       110
           1       1.00      0.97      0.98        90

    accuracy                           0.98       200
   macro avg       0.99      0.98      0.98       200
weighted avg       0.99      0.98      0.98       200



In [37]:
grid.best_params_

{'n_neighbors': 6}